### PR TITLE
All contributors should be listed

### PR DESCRIPTION
**Pull request by mickaelandrieu**
ping @ttoine this update will allow the listing of all contributors on contributors.prestashop.com, no others extra tasks required: the deployment is scripted.

### CODE REVIEW

**Comment by ttoine** [comment]
if this is merged, top contributors will be PrestaShop company employees at 100% (current or previous employees)
while this is legitimate, for the PrestaShop company is actually the biggest contributor to the PrestaShop open source project, this will hide people working for other companies, freelancers and other independent contributors.

A few question to understand better how this board was designed, and what could be possible to do to improve it:

- This is not clear on the actuel generated content: do this board only shows contribution to the core? or on all public repositories? (what about doc, specs, modules, ...?)
- Would it be possible to duplicate that for each repo (at least, core, modules, specs and devdocs), and then have a global board that sum everything? 
- Would it be possible to create a subpage for each contributor, listing the repositories in which they contributed? So, just by clicking on a name, it is possible to see their achievements, and, also, they could share the URL?

If you can find a bit of time to discuss about improvements possibilities, please let me know. I am very interested to learn about it.

**Comment by mickaelandrieu** [comment]
Hi @ttoine,

> while this is legitimate, for the PrestaShop company is actually the biggest contributor to the PrestaShop open source project, this will hide people working for other companies, freelancers and other independent contributors.

this is _why_ it was designed this way in the first place: everything is possible but you need to decide :)

> This is not clear on the actuel generated content: do this board only shows contribution to the core? or on all public repositories? (what about doc, specs, modules, ...?)

While this software is configurated to select the Core repository, it can retrieve the contributions for every repository (even private ones if you are logged in as an authorized user).

> Would it be possible to duplicate that for each repo (at least, core, modules, specs and devdocs), 

Yes, we could have a website for each repository: we only need to deploy multiple instances of TopContributors repository with a different configuration file (ask Laurent for the technical details). This could be a first "easy" step to improve the visibility of the contributors.

> and then have a global board that sum everything?

This need to be created (and designed): it may be a first "easy pick" contribution for a junior developer if someone provide mockups

> Would it be possible to create a subpage for each contributor, listing the repositories in which they contributed? So, just by clicking on a name, it is possible to see their achievements, and, also, they could share the URL?

Everything is possible, I'd say that adding a "profile page" feature into "TopContributors" project is easy and then once we have a dashboard project, we will be able to get a summary of all contributions. Maybe, the contributors project of Api Platform team is open source and may be re-used ?

Cheers

**Comment by ttoine** [comment]
Yes, I know that it was design with a specific purpose, but the needs are evolving.

Instead of having one website per repository, having one page per repository on the contributors.prestashop.com website would be awesome.

Thanks for the answers. I will see how to find time from someone if nobody can do it right now on their time.

**Comment by PierreRambaud** [comment]
Thanks @mickaelandrieu

**Pull request merged**
