### PR TITLE
Sort alphabetically

### PR DESCRIPTION
**Pull request by okom3pom**
I hope I didn't forget a repo

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Sort alphabetically
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     |
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Comment by atomiix** [comment]
I'm not sure we should add native-modules to the list as commits are made automatically by a bot 🤔

**Comment by okom3pom** [comment]
@atomiix i see missing modules for example [blockreassurance](https://github.com/PrestaShop/blockreassurance/)

**Comment by atomiix** [comment]
You're right about blockreassurance! I'm adding it right now!

**Comment by okom3pom** [comment]
I remove the line  'PrestaShop/native-modules', bu i think we can keep the new ordering ?

**Comment by matks** [comment]
Thank you @okom3pom

**Pull request merged**
